server:
  port: 3030

spring:
  application:
    name: CORE-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost